
#spring:
#  application:
#    name: outline
#  # 数据库配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.mysql.cj.jdbc.MysqlDataSource
#    url: jdbc:mysql://localhost:3306/outline_system?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: Pyq-20210305
#server:
#  port: 8888
#  servlet:
#    session:
#      timeout: 30m
#    context-path: /
#  tomcat:
#    uri-encoding: utf-8
#    threads:
#      max: 200
#mybatis-plus:
#  type-enums-package: com.ujs.outline.domain.enums

spring:
  application:
    name: outline
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://localhost:3306/学校课程管理系统?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: sh20060401
server:
  port: 80
  servlet:
    session:
      timeout: 30m
    context-path: /
  tomcat:
    uri-encoding: utf-8
    threads:
      max: 200

mybatis-plus:
  type-enums-package: com.ujs.outline.domain.enums